resources:
- ./../base
#namePrefix: dev-
namespace: mc-sock-shop

patches:
- path: 23-shipping-dep.yaml
- path: 10-front-end-svc.yaml
#- path: .argocd-source-sock-shop.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: weaveworksdemos/shipping
  newName: ghcr.io/utvecklarbolaget-backend/weaveworksdemos/shipping
  newTag: 0.4.0
